### ISSUE TITLE
Kubernetes example doesn't work

### ISSUE THREAD

**Issue by resouer** [ceph/ceph-docker#165]
Followed the guide: https://github.com/ceph/ceph-docker/blob/master/examples/kubernetes/ceph-mon-v1.json

I have two Pods running, one is 151, another is 153

Problem:

```
sudo mount -t ceph  10.10.102.153:/ /mnt/mycephfs -o name=admin,secret=AQDJw0JW6mLINRAAHpyn52W5VvzOr4T2r3hV5g==
mount error 5 = Input/output error
```

In monitor container:
```
root@ubuntu:/# ceph -s
    cluster 72b30bd3-fbe1-483c-b55a-5c9fda39a245
     health HEALTH_ERR
            64 pgs stuck inactive
            64 pgs stuck unclean
            no osds
     monmap e1: 1 mons at {ubuntu=10.10.102.153:6789/0}
            election epoch 2, quorum 0 ubuntu
     osdmap e1: 0 osds: 0 up, 0 in
      pgmap v2: 64 pgs, 1 pools, 0 bytes data, 0 objects
            0 kB used, 0 kB / 0 kB avail
                  64 creating

root@ubuntu:/# ceph mds stat 
e1: 0/0/0 up

```

yaml file I used:
```
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: ceph-mon
  labels:
    name: serving
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: ceph-mon
    spec:
      volumes:
      - name: cephconfig
        hostPath:
          path: "/etc/ceph/"
      - name: cephdata
        hostPath:
          path: "/var/lib/ceph/"
      containers:
      - name: ceph-mon-pod
        image: ceph/daemon
        env:
        - name: CEPH_DAEMON
          value: MON
        - name: CEPH_PUBLIC_NETWORK
          value: 10.10.102.0/24
        - name: MON_IP_AUTO_DETECT
          value: '1'
        volumeMounts:
        - name: cephconfig
          mountPath: "/etc/ceph/"
        - name: cephdata
          mountPath: "/var/lib/ceph/"
```

It also doesn't work even I set ` hostNetwork=true`
