### ISSUE TITLE
Ceph/Demo: RBD usage

### ISSUE THREAD

**Issue by dopykuh** [ceph/ceph-docker#571]
Hey,

i'am trying to use your ceph/demo container with an dockerized environment. (Container is privileged)

GitlabCI config:

```yaml
ceph:
  image: ubuntu
  script:
    - apt update && apt install -y docker.io
    - service docker start
    - sleep 1
    - docker ps
    - ip l a dummy_moo type dummy
    - ip a add 192.168.0.20/24 dev dummy_moo
    - ip l s dummy_moo up
    - docker run -d --name cephdemo --net=host -v /etc/ceph:/etc/ceph -e MON_IP=192.168.0.20 -e CEPH_PUBLIC_NETWORK=192.168.0.0/24 ceph/demo
    - sleep 30
    - docker logs $(docker ps -q) 
    - docker exec cephdemo ceph -s
    - docker exec cephdemo rbd ls
```

Ceph is up and running, but `rbd ls` hangs.

```bash
$ docker exec cephdemo ceph -s
    cluster b2a98159-85b8-40c2-9f26-a9df4e51273b
     health HEALTH_OK
     monmap e1: 1 mons at {runner-9beb5f58-project-92-concurrent-0=192.168.0.20:6789/0}
            election epoch 3, quorum 0 runner-9beb5f58-project-92-concurrent-0
      fsmap e2: 0/0/1 up
     osdmap e8: 1 osds: 0 up, 0 in
            flags sortbitwise
      pgmap v9: 88 pgs, 4 pools, 0 bytes data, 0 objects
            0 kB used, 0 kB / 0 kB avail
                  88 creating
$ docker exec cephdemo rbd ls
# timed out
```

Any ideas what i'm doing wrong?
