### ISSUE TITLE
ceph-mon: error generating initial monmap: (22) Invalid argument

### ISSUE THREAD

**Issue by osixia** [ceph/ceph-docker#573]
Just tried the kubernetes example with a daemon set and get the following error:

```
monmaptool: monmap file /etc/ceph/monmap-osixia-system
monmaptool: set fsid to 8970119c-3b7f-4fb1-af17-7fbc6b0410d7
monmaptool: writing epoch 0 to /etc/ceph/monmap-osixia-system (2 monitors)
importing contents of /var/lib/ceph/bootstrap-osd/osixia-system.keyring into /etc/ceph/osixia-system.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/osixia-system.keyring into /etc/ceph/osixia-system.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/osixia-system.keyring into /etc/ceph/osixia-system.mon.keyring
importing contents of /etc/ceph/osixia-system.client.admin.keyring into /etc/ceph/osixia-system.mon.keyring
unable to parse addrs in 'ceph-mon'
ceph-mon: warning: no initial monitors; must use admin socket to feed hints
server name not found: ceph-mon (Temporary failure in name resolution)
ceph-mon: set fsid to 8970119c-3b7f-4fb1-af17-7fbc6b0410d7
ceph-mon: created monfs at /var/lib/ceph/mon/osixia-system-ceph-mon-69d8g for mon.ceph-mon-69d8g
2017-03-28 15:53:32  /entrypoint.sh: SUCCESS
2017-03-28 15:53:32.426755 7f5377f1f840  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-03-28 15:53:32.426789 7f5377f1f840  0 ceph version 11.2.0 (f223e27eeb35991352ebc1f67423d4ebc252adb7), process ceph-mon, pid 1
2017-03-28 15:53:32.426938 7f5377f1f840  0 pidfile_write: ignore empty --pid-file
2017-03-28 15:53:32.439341 7f5377f1f840  0 load: jerasure load: lrc load: isa 
2017-03-28 15:53:32.439893 7f5377f1f840  1 leveldb: Recovering log #3
2017-03-28 15:53:32.439980 7f5377f1f840  1 leveldb: Level-0 table #5: started
2017-03-28 15:53:32.445977 7f5377f1f840  1 leveldb: Level-0 table #5: 946 bytes OK
2017-03-28 15:53:32.474430 7f5377f1f840  1 leveldb: Delete type=3 #2

2017-03-28 15:53:32.474569 7f5377f1f840  1 leveldb: Delete type=0 #3

unable to parse addrs in 'ceph-mon'
usage: ceph-mon -i monid [flags]
  --debug_mon n
        debug monitor level (e.g. 10)
  --mkfs
        build fresh monitor fs
  --force-sync
        force a sync from another mon by wiping local data (BE CAREFUL)
  --yes-i-really-mean-it
        mandatory safeguard for --force-sync
  --compact
        compact the monitor store
  --osdmap <filename>
        only used when --mkfs is provided: load the osdmap from <filename>
  --inject-monmap <filename>
        write the <filename> monmap to the local monitor store and exit
  --extract-monmap <filename>
        extract the monmap from the local monitor store and exit
  --mon-data <directory>
        where the mon store and keyring are located
2017-03-28 15:53:32.480946 7f5377f1f840 -1 /usr/bin/ceph-mon: error generating initial monmap: (22) Invalid argument
server name not found: ceph-mon (Temporary failure in name resolution)
  --conf/-c FILE    read configuration from the given configuration file
  --id/-i ID        set ID portion of my name
  --name/-n TYPE.ID set name
  --cluster NAME    set cluster name (default: ceph)
  --setuser USER    set uid to user or uid (and gid to user's gid)
  --setgroup GROUP  set gid to group or gid
  --version         show version and quit

  -d                run in foreground, log to stderr.
  -f                run in foreground, log to usual location.
  --debug_ms N      set message debug level (e.g. 1)
```

DaemonSet:
```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: ceph
    daemon: mon
  name: ceph-mon
  namespace: osixia-system
spec:
  template:
    metadata:
      name: ceph-mon
      namespace: ceph
      labels:
        app: ceph
        daemon: mon
    spec:
      nodeSelector:
        ceph-mon: "true"
      serviceAccount: default
      volumes:
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
      containers:
        - name: ceph-mon
          image: ceph/daemon:tag-build-master-kraken-ubuntu-16.04
          imagePullPolicy: Always
          lifecycle:
            preStop:
                exec:
                  # remove the mon on Pod stop.
                  command:
                    - "/remove-mon.sh"
          ports:
            - containerPort: 6789
          env:
            - name: CEPH_DAEMON
              value: MON
            - name: KV_TYPE
              value: k8s
            - name: NETWORK_AUTO_DETECT
              value: "4"
            - name: CLUSTER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
          livenessProbe:
              tcpSocket:
                port: 6789
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6789
              timeoutSeconds: 5
```
Note that I use i custom cluster name set to "osixia-system" (pod namespace) a took care to change the filenames in the secrets accordingly so I don't think the error comes from that.
